[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 1

[[main]]
  identifier = "publication"
  name = "Publications"
  url = "publication"
  weight = 2

[[main]]
  identifier = "resume"
  name = "Resume"
  url = "resume"
  weight = 3

[[main]]
  identifier = "showcase"
  name = "Projects"
  url = "showcase"
  weight = 4
