[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 1

[[main]]
  identifier = "resume"
  name = "Resume"
  url = "resume"
  weight = 2

[[main]]
  identifier = "showcase"
  name = "Showcase"
  url = "showcase"
  weight = 3

[[main]]
  identifier = "gallery"
  name = "Gallery"
  url = "gallery"
  weight = 4
