[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 1

[[main]]
  identifier = "showcase"
  name = "Showcase"
  url = "showcase"
  weight = 2

[[main]]
  identifier = "gallery"
  name = "Gallery"
  url = "gallery"
  weight = 3
    
[[main]]
  parent = "gallery"
  name = "Animation"
  url = "gallery/animation"

[[main]]
  parent = "gallery"
  name = "Photo"
  url = "gallery/photo"
