baseURL = ""
languageCode = "en-us"
title = "Haochen Shi"
theme = "m10c"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/"
  [[menu.main]]
    identifier = "resume"
    name = "Resume/CV"
    url = "/static/resume.pdf"

[params]
  avatar = "/static/avatar.jpg"
  favicon = "/static/favicon.ico"
  author = "Haochen Shi"
  description = "Undergraduate at UW-Madision"
  menu_item_separator = " - "
  [[params.social]]
    name = "github"
    url = "https://github.com/hashiyaa"