baseURL = ""
languageCode = "en-us"
title = "Haochen Shi"
theme = "m10c"
avatar = "/static/avatar.jpg"
favicon = "/static/favicon.ico"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
  [[menu.main]]
    identifier = "resume"
    name = "Resume/CV"
    url = "/resume.pdf"

[params]
  author = "Haochen Shi"
  description = "Undergraduate at UW-Madision"
  menu_item_separator = " - "
  [[params.social]]
    name = "github"
    url = "https://github.com/hashiyaa"